Created 404 Page
coding-blocks/gondor pull request #58
Opened 2020-05-17 16:50 UTC by prathambatra

fixes #20 
Signed-off-by: prathambatra <batrapratham999@gmail.com>

2020-05-17 16:51 UTC, prathambatra commented
![Screenshot from 2020-05-17 22-17-22](https://user-images.githubusercontent.com/29707062/82154609-a936b680-988c-11ea-90f2-8bc7575a1416.png)
![Screenshot from 2020-05-17 22-17-33](https://user-images.githubusercontent.com/29707062/82154612-af2c9780-988c-11ea-936e-6a28e004fb6a.png)

2020-05-17 16:51 UTC, prathambatra commented
@hereisnaman please review.

2020-05-17 17:09 UTC, hereisnaman commented
No need to render navbar and sidebar

2020-05-17 17:09 UTC, hereisnaman commented
Center align the component with col-8 width

2020-05-17 17:22 UTC, prathambatra commented
okay doing changes

2020-05-17 17:50 UTC, prathambatra commented
@hereisnaman I have done the required changes.

2020-05-17 19:05 UTC, prathambatra commented
@hereisnaman please check.

2020-05-17 19:09 UTC, 0xnmn requested changes

2020-05-17 19:09 UTC, hereisnaman commented on app/components/PageNotFound/index.js
> +    <div className="col-8 col-centre text-center">
No col-center required. use offset classes. Let it be col-12 and col-md-8. Also move the col classes to the custom404 component.

2020-05-17 19:09 UTC, hereisnaman commented on app/components/PageNotFound/style.scss
> +.col-centre {
not required.

2020-05-17 19:09 UTC, hereisnaman commented on app/pages/404.js
> +    </div>
Wrap whole thing inside a '.row' and more the col classes here.

2020-05-17 19:33 UTC, prathambatra commented
@hereisnaman  done

2020-05-18 08:51 UTC, prathambatra commented
@hereisnaman have a look.

2020-05-18 13:54 UTC, hereisnaman commented
> @hereisnaman have a look.

Can you add updated screnshots?

2020-05-18 13:57 UTC, prathambatra commented
> > @hereisnaman have a look.
> 
> Can you add updated screnshots?

![Screenshot from 2020-05-18 01-01-43](https://user-images.githubusercontent.com/29707062/82221471-a9db5580-993d-11ea-95ce-f27c37223433.png)

2020-05-18 14:00 UTC, 0xnmn approved these changes

2020-05-18 14:00 UTC, merged