Hide Navbar and Sidebar based on query params fixes#56
coding-blocks/gondor pull request #61
Opened 2020-05-17 19:12 UTC by jugshaurya

2020-05-17 19:14 UTC, jugshaurya commented
@hereisnaman, Please review.

2020-05-17 19:34 UTC, 0xnmn requested changes

2020-05-17 19:34 UTC, hereisnaman commented on app/layouts/Dashboard/index.js
> +
remove the blank line

2020-05-17 19:34 UTC, hereisnaman commented on app/layouts/Dashboard/index.js
> +  const isEmbedAvailable = useRouter().query.hasOwnProperty('embed');
The hooks should not be conditionally rendered. This should be the first line inside the function.

rename to `isEmbed`.

2020-05-17 19:34 UTC, hereisnaman commented on app/layouts/Dashboard/index.js
> +      <main className={classNames({ 'embed-style': isEmbedAvailable })}>
rename class to `embed`

2020-05-17 19:34 UTC, hereisnaman commented on app/layouts/Dashboard/style.scss
> +    &.embed-style {
rename class to embed

2020-05-18 04:28 UTC, jugshaurya commented on app/layouts/Dashboard/index.js
> +
should this extra line be removed?

2020-05-18 04:29 UTC, jugshaurya commented
@hereisnaman, please review

2020-05-18 04:31 UTC, 0xnmn approved these changes

2020-05-18 04:31 UTC, merged